### ISSUE TITLE
Fix: MiniBatch - get RNN to memorize a training sample of 10 within 1k epoch

### ISSUE THREAD

**Issue by itchingpixels** [applied-exploration/integer-sequence#22]
It looks like since the mini-batch implementation, loss never goes below 1, no matter how many epochs we train on. I haven't managed to get test set accuracy above 2-3% after mini-batch, even with 400k epoch.

Two test files:

On current `main`, after mini-batch:
https://github.com/applied-exploration/integer-sequence/blob/main/function-gen/test_rnn_plain.py
Loss @ 1k epoch: ~1

On `pre-minibatch`, before mini-batch:
https://github.com/applied-exploration/integer-sequence/blob/pre-minibatch/function-gen/test_rnn_plain.py
Loss @ 1k epoch: ~0

**Comment by szemyd** [comment]
A few important notes:

If the dataset is fed sequentially to the minibatch generator and set num_batch to 1, that simulates what we would have if we had pre-minibatch implementation.

Instead of: 
```
input_tensor_minibatch = self.create_minibatch(input_data, self.batch_size, input_lang)
target_tensor_minibatch = self.create_minibatch(target_data, self.batch_size, output_lang)
```
We feed it in one by one:
```
input_tensor_minibatch = self.create_minibatch([input_data[(i-1)%len(input_data)]], self.batch_size, input_lang)
target_tensor_minibatch = self.create_minibatch([target_data[(i-1)%len(target_data)]], self.batch_size, output_lang)
```
where i is the step in the epochs.

This equally brings the loss down to pre-minibatch results (close to 0.0).

This means that the ranomized nature of the minibatch generation heavily influences the loss we get. It seems the network accepts and digests a minibatch correctly.

**Comment by szemyd** [comment]
Found the bug.

When creating the minibatch we were randomizing it separately, meaning input and target were mixed up.
Both times create_minibatch was called it created a separate random list.

```python
encoded_dataset = [tensorFromSentence(lang, data[random.randrange(0, len(data))])
                for i in range(batch_size)]
```

Going to push a fix.
